-- Human label for the lifecycle version chain (#480). NULL for hand-
-- edited customizations; populated with `default-bootstrap` for the
-- autogenerated v1 of a new project and with the stock template id
-- (`generic-careful`, `nextjs-vercel`, …) when a template is applied.

alter table "lifecycles"
  add column if not exists "name" text;
