import { DEFAULT_MERGECREW_YAML } from '@mergecrew/config-yaml';
import type { InceptionSummary } from './types.js';

/**
 * Build a draft `mergecrew.yaml` for a freshly-cloned repo. The body is
 * the standard default lifecycle (so the user gets a known-good starting
 * point); we prepend a comment block summarizing what Inception found so
 * the user can spot misclassifications before saving.
 *
 * We deliberately do NOT mutate the lifecycle based on the summary.
 * Auto-tweaks (e.g. switching the `deploy_dev` agent's adapter) belong in
 * the setup wizard where the user confirms each one. Inception's job is to
 * surface evidence; the wizard turns evidence into config.
 */
export function buildDraftYaml(summary: InceptionSummary): string {
  return `${renderHeader(summary)}\n${DEFAULT_MERGECREW_YAML}`;
}

function renderHeader(summary: InceptionSummary): string {
  const lines: string[] = [
    '# ─── Project Inception summary ─────────────────────────────────────────────',
    '# Auto-generated by Mergecrew on first connect. The body below is the',
    '# default lifecycle — review it in the setup wizard and adjust any of the',
    '# auto-detected items before the first daily run.',
    '#',
  ];

  if (summary.frameworks.length > 0) {
    lines.push('# Stack:');
    for (const f of summary.frameworks) {
      lines.push(`#   - ${f.label}    (${f.evidence})`);
    }
  } else {
    lines.push('# Stack: (none detected — tsconfig + package.json missing or unreadable)');
  }
  lines.push('#');

  const testScripts = summary.scripts.filter((s) => s.kind === 'test');
  const lintScripts = summary.scripts.filter((s) => s.kind === 'lint');
  const buildScripts = summary.scripts.filter((s) => s.kind === 'build');
  const typeScripts = summary.scripts.filter((s) => s.kind === 'typecheck');
  if (
    testScripts.length + lintScripts.length + buildScripts.length + typeScripts.length >
    0
  ) {
    lines.push('# Scripts the QA agent will probably want to run:');
    for (const s of [...typeScripts, ...lintScripts, ...testScripts, ...buildScripts]) {
      lines.push(`#   - ${s.kind.padEnd(9)} ${s.name.padEnd(18)} ${s.cmd}`);
    }
    lines.push('#');
  }

  const deployCandidates = summary.workflows.filter((w) => w.isDeployCandidate);
  if (deployCandidates.length > 0) {
    lines.push('# Deploy-workflow candidates (pick one in the setup wizard):');
    for (const w of deployCandidates) {
      const corr = w.acceptsCorrelationId
        ? 'accepts mergecrew_correlation_id'
        : 'NO mergecrew_correlation_id input — Mergecrew will offer to add it';
      lines.push(`#   - ${w.path}    [${w.events.join(',')}]    ${corr}`);
    }
    lines.push('#');
  } else if (summary.workflows.length > 0) {
    lines.push('# Workflows found, none look like deploys — configure dev_deploy manually:');
    for (const w of summary.workflows) {
      lines.push(`#   - ${w.path}    [${w.events.join(',')}]`);
    }
    lines.push('#');
  } else {
    lines.push('# No GitHub Actions workflows found — Mergecrew will scaffold one in the wizard.');
    lines.push('#');
  }

  lines.push('# ───────────────────────────────────────────────────────────────────────────');
  return lines.join('\n');
}
