import dgram from 'node:dgram';
import pino from 'pino';
import { isHostAllowed, parseAllowlistEnv } from './allowlist.js';
import { buildNxdomain, DnsParseError, parseQuery } from './dns-message.js';

/**
 * Mergecrew runner DNS resolver (#574).
 *
 * Listens on UDP `RUNNER_DNS_PORT` (default 53) and answers queries
 * with NXDOMAIN unless the hostname is on the allowlist supplied via
 * `RUNNER_DNS_ALLOWLIST`. Allowed queries are forwarded verbatim to
 * `RUNNER_DNS_UPSTREAM` (default 1.1.1.1:53). Every blocked attempt
 * is JSON-logged with `(host, src_ip)` for audit.
 *
 * The resolver is layered with the nftables ruleset from #573:
 * nftables drops by IP, this drops by name. Together they close the
 * "build script resolves a bad host then connects by IP" hole.
 *
 * Per-run resolver instances (one process per sandbox, with project-
 * scoped allowlists) is a follow-up. V1 ships a host-global allowlist
 * (the union of all active projects' allowlists, generated by the
 * operator's config-management).
 */

const logger = pino({
  level: process.env.LOG_LEVEL ?? 'info',
  base: { service: 'runner-dns' },
  ...(process.env.NODE_ENV !== 'production'
    ? { transport: { target: 'pino-pretty', options: { colorize: true } } }
    : {}),
});

const PORT = Number(process.env.RUNNER_DNS_PORT ?? 53);
const ALLOWLIST = parseAllowlistEnv(process.env.RUNNER_DNS_ALLOWLIST);
const UPSTREAM = parseUpstream(process.env.RUNNER_DNS_UPSTREAM ?? '1.1.1.1:53');
const FORWARD_TIMEOUT_MS = Number(process.env.RUNNER_DNS_TIMEOUT_MS ?? 5000);

function parseUpstream(raw: string): { host: string; port: number } {
  const [host, port] = raw.split(':');
  return { host: host ?? '1.1.1.1', port: Number(port ?? 53) };
}

const server = dgram.createSocket('udp4');

server.on('message', (msg, rinfo) => {
  let parsed;
  try {
    parsed = parseQuery(msg);
  } catch (err: any) {
    logger.warn({ src: rinfo.address, err: err?.message ?? String(err) }, 'dropping malformed DNS query');
    return;
  }
  const q = parsed.questions[0];
  if (!q) return;
  const host = q.name;
  if (!isHostAllowed(host, ALLOWLIST)) {
    logger.info({ event: 'dns.blocked', host, src: rinfo.address }, 'NXDOMAIN');
    server.send(buildNxdomain(msg), rinfo.port, rinfo.address);
    return;
  }
  // Forward to upstream. Each forwarded query gets its own ephemeral
  // socket so concurrent queries don't stomp each other.
  const fwd = dgram.createSocket('udp4');
  const timer = setTimeout(() => {
    logger.warn({ host, src: rinfo.address, upstreamTimeoutMs: FORWARD_TIMEOUT_MS }, 'upstream DNS timeout');
    try { fwd.close(); } catch {}
  }, FORWARD_TIMEOUT_MS);
  fwd.on('message', (reply) => {
    clearTimeout(timer);
    server.send(reply, rinfo.port, rinfo.address);
    try { fwd.close(); } catch {}
  });
  fwd.on('error', (err) => {
    clearTimeout(timer);
    logger.warn({ host, err: err.message }, 'upstream DNS error');
    try { fwd.close(); } catch {}
  });
  fwd.send(msg, UPSTREAM.port, UPSTREAM.host);
});

server.on('listening', () => {
  const addr = server.address();
  logger.info({ port: addr.port, address: addr.address, allowlistSize: ALLOWLIST.length, upstream: UPSTREAM }, 'runner-dns: listening');
});

server.on('error', (err) => {
  logger.error({ err: err.message }, 'runner-dns: socket error');
  process.exit(1);
});

server.bind(PORT);

function shutdown(): void {
  logger.info('runner-dns: shutting down');
  server.close(() => process.exit(0));
  setTimeout(() => process.exit(1), 5000).unref();
}
process.on('SIGINT', shutdown);
process.on('SIGTERM', shutdown);
