import { Injectable } from '@nestjs/common';
import { mkdtemp, writeFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { GitHubProvider, getGitHubAppCredentials } from '@mergecrew/adapters-vcs';
import { GitHubActionsProvider } from '@mergecrew/adapters-deploy';
import { effectiveBaseBranch } from '@mergecrew/db';
import { ValidationError } from '@mergecrew/domain';
import { PrismaService } from '../../common/prisma.service.js';
import { TenantContextService } from '../../common/tenant-context.service.js';

export interface SmokeTestResult {
  prUrl: string;
  prNumber: number;
  branch: string;
  deployStatus: 'success' | 'failed' | 'cancelled' | 'timeout';
  devUrl: string | null;
  workflowRunId: string;
  durationMs: number;
}

/**
 * Onboarding smoke test (V1.1, #7).
 *
 * The "does this round-trip even work?" check from J1 step 5: open a
 * no-op PR against the connected repo, dispatch the dev deploy workflow,
 * await completion, return the resulting URL. This is the same shape as
 * `apps/dogfood-smoke` but invoked from the web UI on demand.
 *
 * The PR is opened in DRAFT and left open so a human reviewer can confirm
 * the round-trip and close it. Mergecrew never auto-merges smoke PRs —
 * onboarding signals work, then the user decides what to do.
 */
@Injectable()
export class SmokeTestService {
  constructor(
    private prisma: PrismaService,
    private tenant: TenantContextService,
  ) {}

  async run(projectSlug: string): Promise<SmokeTestResult> {
    const t = this.tenant.require();
    const project = await this.prisma.withTenant(t.organizationId, (tx) =>
      tx.project.findFirst({
        where: { slug: projectSlug, organizationId: t.organizationId },
        include: { connectedRepo: true },
      }),
    );
    if (!project) throw new ValidationError('project not found');
    const repo = project.connectedRepo;
    if (!repo) {
      throw new ValidationError(
        'no repository connected — install the GitHub App and connect a repo first',
      );
    }
    const dt = await this.prisma.withTenant(t.organizationId, (tx) =>
      tx.deployTarget.findFirst({ where: { projectId: project.id, kind: 'dev' } }),
    );
    if (!dt) {
      throw new ValidationError(
        'no dev deploy target configured — set one under Deploy targets first',
      );
    }
    if (dt.adapterId !== 'github-actions') {
      throw new ValidationError(
        `smoke test only supports the github-actions adapter today; this project's dev target is ${dt.adapterId}`,
      );
    }
    const creds = getGitHubAppCredentials();
    if (!creds) {
      throw new ValidationError(
        'smoke test requires GITHUB_APP_ID and GITHUB_APP_PRIVATE_KEY',
      );
    }

    const vcs = new GitHubProvider(creds);
    const deploy = new GitHubActionsProvider({
      appId: creds.appId,
      privateKey: creds.privateKey,
    });

    const branch = `mergecrew-smoke/${new Date().toISOString().replace(/[:.]/g, '-')}`;
    const correlationId = `smoke-${Date.now().toString(36)}`;
    const startedAt = Date.now();
    const workspace = await mkdtemp(path.join(tmpdir(), 'mergecrew-smoke-'));

    const baseBranch = effectiveBaseBranch(repo);
    try {
      await vcs.cloneIntoWorkspace(
        {
          installationId: repo.installationId,
          repoId: repo.repoId ?? undefined,
          repoFullName: repo.repoFullName,
          defaultBranch: baseBranch,
        },
        baseBranch,
        workspace,
      );
      await vcs.createBranch(workspace, branch, baseBranch);
      await writeFile(
        path.join(workspace, '.mergecrew-smoke'),
        `mergecrew smoke ${correlationId} at ${new Date().toISOString()}\n`,
      );
      const sha = await vcs.commit(workspace, {
        message: `chore: mergecrew onboarding smoke ${correlationId}`,
        authorName: 'Mergecrew Smoke',
        authorEmail: 'smoke@mergecrew.dev',
      });
      await vcs.push(workspace, branch);
      const pr = await vcs.openPullRequest(
        {
          installationId: repo.installationId,
          repoId: repo.repoId ?? undefined,
          repoFullName: repo.repoFullName,
          defaultBranch: baseBranch,
        },
        {
          head: branch,
          base: baseBranch,
          title: `[smoke] mergecrew onboarding ${correlationId}`,
          body: [
            '<!-- mergecrew onboarding smoke -->',
            '',
            'Auto-generated by the project setup wizard to confirm the dev-deploy',
            'round-trip. Safe to close — the marker file is the only change.',
          ].join('\n'),
          draft: true,
        },
      );

      const targetRef = {
        id: dt.id,
        kind: dt.kind as 'dev' | 'staging' | 'prod',
        adapterId: dt.adapterId,
        config: (dt.config ?? {}) as Record<string, unknown>,
      };
      const handle = await deploy.triggerDeploy(targetRef, {
        ref: sha,
        branch,
        correlationId,
      });

      const timeoutMs = Number(process.env.SMOKE_TEST_TIMEOUT_MS ?? 5 * 60_000);
      const abort = new AbortController();
      const result = await deploy.awaitCompletion(handle, timeoutMs, abort.signal);
      const deployStatus =
        result.status.kind === 'success'
          ? 'success'
          : result.status.kind === 'cancelled'
          ? 'cancelled'
          : result.status.kind === 'failed' &&
              (result.status as { reason?: string }).reason === 'timeout'
            ? 'timeout'
            : 'failed';
      const devUrl =
        result.url ??
        (await deploy.resolveUrlForRef(targetRef, branch).catch(() => null));

      return {
        prUrl: pr.url,
        prNumber: pr.number,
        branch,
        deployStatus,
        devUrl: devUrl ?? null,
        workflowRunId: handle.externalRunId,
        durationMs: Date.now() - startedAt,
      };
    } finally {
      await rm(workspace, { recursive: true, force: true }).catch(() => {});
    }
  }
}
