/* eslint-disable no-console */
/**
 * `pnpm dogfood:bake-report` — generates the V1-dogfood comparison
 * table for issue #565. Reads the recent TimelineEvent log + the
 * AgentStep table and prints process-vs-docker metrics for the
 * before/after rollout window.
 *
 * The 14-day operational bake gates flipping `RUNNER_SANDBOX` from
 * `process` → `docker` as the default. The report needs to live in
 * code (not in someone's notebook) so the same numbers can be
 * regenerated by the next operator who runs into this issue.
 *
 * Inputs:
 *   --before-from / --before-to : ISO timestamps for the process window
 *   --after-from  / --after-to  : ISO timestamps for the docker window
 *   --org <slug>                : optional, scope to a single org
 *
 * Defaults:
 *   before window = 14 days ending at midnight UTC of `--flip-at` (or
 *                   `--after-from` if not supplied)
 *   after window  = 14 days starting at `--flip-at`
 *
 * Pulls:
 *   - SANDBOX_STARTED (#565) → cold-start ms p50/p95, per driver.
 *   - AgentStep.status / startedAt / finishedAt → pass rate + p50/p95 step latency.
 *   - egress.blocked logs are NOT in the eventlog (they live in the
 *     runner-egress-proxy logs); this report leaves that row blank
 *     and the operator pastes the value from their log shipper.
 *   - OOM kills: the docker driver emits `sandbox.oom_suspected` to
 *     pino only (no timeline event by design — it's a debug signal,
 *     not a tenant-visible event). Same caveat as egress.
 *
 * Usage:
 *   pnpm dogfood:bake-report --flip-at 2026-05-25T00:00:00Z
 *   pnpm dogfood:bake-report --before-from 2026-05-11 --before-to 2026-05-25 \
 *                            --after-from  2026-05-25 --after-to  2026-06-08
 */
import { withSystem } from '@mergecrew/db';

interface Window {
  from: Date;
  to: Date;
}

interface DriverMetrics {
  stepsRun: number;
  stepsPassed: number;
  p50StepMs: number | null;
  p95StepMs: number | null;
  p50ColdStartMs: number | null;
  p95ColdStartMs: number | null;
}

function flagValue(argv: string[], name: string): string | undefined {
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === undefined) continue;
    if (a === name) return argv[i + 1];
    if (a.startsWith(`${name}=`)) return a.slice(name.length + 1);
  }
  return undefined;
}

function parseWindow(argv: string[]): { before: Window; after: Window; orgSlug?: string } {
  const orgSlug = flagValue(argv, '--org');
  const flipAt = flagValue(argv, '--flip-at');
  const beforeFrom = flagValue(argv, '--before-from');
  const beforeTo = flagValue(argv, '--before-to');
  const afterFrom = flagValue(argv, '--after-from');
  const afterTo = flagValue(argv, '--after-to');

  if (beforeFrom && beforeTo && afterFrom && afterTo) {
    return {
      before: { from: new Date(beforeFrom), to: new Date(beforeTo) },
      after: { from: new Date(afterFrom), to: new Date(afterTo) },
      ...(orgSlug ? { orgSlug } : {}),
    };
  }
  if (!flipAt) {
    throw new Error(
      'either --flip-at <iso> or all four of --before-from/--before-to/--after-from/--after-to are required',
    );
  }
  const flip = new Date(flipAt);
  const fourteenDays = 14 * 24 * 60 * 60 * 1000;
  return {
    before: { from: new Date(flip.getTime() - fourteenDays), to: flip },
    after: { from: flip, to: new Date(flip.getTime() + fourteenDays) },
    ...(orgSlug ? { orgSlug } : {}),
  };
}

function percentile(sorted: number[], p: number): number | null {
  if (sorted.length === 0) return null;
  const idx = Math.min(sorted.length - 1, Math.floor((sorted.length - 1) * p));
  return sorted[idx] ?? null;
}

async function collect(window: Window, orgSlug?: string): Promise<Record<string, DriverMetrics>> {
  return withSystem(async (tx) => {
    let orgId: string | undefined;
    if (orgSlug) {
      const org = await tx.organization.findUnique({
        where: { slug: orgSlug },
        select: { id: true },
      });
      if (!org) throw new Error(`org not found: ${orgSlug}`);
      orgId = org.id;
    }

    // AgentSteps that started within the window. We bucket per-driver
    // by joining to the SANDBOX_STARTED timeline event — a step
    // without that event predates #565 and only contributes to the
    // pass-rate / step-latency totals, not the cold-start columns.
    const steps = await tx.agentStep.findMany({
      where: {
        startedAt: { gte: window.from, lt: window.to },
        ...(orgId ? { organizationId: orgId } : {}),
      },
      select: {
        id: true,
        status: true,
        startedAt: true,
        finishedAt: true,
      },
    });

    const sandboxEvents = await tx.timelineEvent.findMany({
      where: {
        type: 'SANDBOX_STARTED',
        occurredAt: { gte: window.from, lt: window.to },
        ...(orgId ? { organizationId: orgId } : {}),
      },
      select: {
        agentStepId: true,
        payload: true,
      },
    });

    const driverByStep = new Map<string, { driver: string; coldStartMs: number }>();
    for (const e of sandboxEvents) {
      if (!e.agentStepId) continue;
      const p = e.payload as { driver?: string; coldStartMs?: number } | null;
      const driver = p?.driver ?? 'unknown';
      const coldStartMs = typeof p?.coldStartMs === 'number' ? p.coldStartMs : 0;
      driverByStep.set(e.agentStepId, { driver, coldStartMs });
    }

    // Pre-#565 / process-driver steps (no SANDBOX_STARTED event):
    // bucket them under 'process' since that's the only driver that
    // didn't emit the event before this PR. Once #565 ships we never
    // see this case for new steps — but the BEFORE window will hit
    // it for every row, which is exactly the desired baseline.
    const byDriver: Record<string, {
      stepsRun: number;
      stepsPassed: number;
      stepLatenciesMs: number[];
      coldStartsMs: number[];
    }> = {};
    const ensure = (k: string) => {
      if (!byDriver[k]) {
        byDriver[k] = { stepsRun: 0, stepsPassed: 0, stepLatenciesMs: [], coldStartsMs: [] };
      }
      return byDriver[k]!;
    };

    for (const s of steps) {
      const meta = driverByStep.get(s.id);
      const driver = meta?.driver ?? 'process';
      const b = ensure(driver);
      b.stepsRun += 1;
      if (s.status === 'completed' || s.status === 'succeeded' || s.status === 'passed') {
        b.stepsPassed += 1;
      }
      if (s.startedAt && s.finishedAt) {
        b.stepLatenciesMs.push(s.finishedAt.getTime() - s.startedAt.getTime());
      }
      if (meta && meta.coldStartMs > 0) {
        b.coldStartsMs.push(meta.coldStartMs);
      }
    }

    const out: Record<string, DriverMetrics> = {};
    for (const [driver, b] of Object.entries(byDriver)) {
      const stepsSorted = [...b.stepLatenciesMs].sort((a, c) => a - c);
      const coldSorted = [...b.coldStartsMs].sort((a, c) => a - c);
      out[driver] = {
        stepsRun: b.stepsRun,
        stepsPassed: b.stepsPassed,
        p50StepMs: percentile(stepsSorted, 0.5),
        p95StepMs: percentile(stepsSorted, 0.95),
        p50ColdStartMs: percentile(coldSorted, 0.5),
        p95ColdStartMs: percentile(coldSorted, 0.95),
      };
    }
    return out;
  });
}

function fmtMs(v: number | null): string {
  if (v == null) return 'n/a';
  if (v >= 1000) return `${(v / 1000).toFixed(1)}s`;
  return `${v}ms`;
}

function fmtPct(num: number, den: number): string {
  if (den === 0) return 'n/a';
  return `${((num / den) * 100).toFixed(2)}% (${num}/${den})`;
}

async function main(): Promise<void> {
  const argv = process.argv.slice(2);
  const { before, after, orgSlug } = parseWindow(argv);

  console.log(`Dogfood bake report — issue #565`);
  console.log(`Org filter         : ${orgSlug ?? '(all)'}`);
  console.log(`Before (process)   : ${before.from.toISOString()} → ${before.to.toISOString()}`);
  console.log(`After  (docker)    : ${after.from.toISOString()} → ${after.to.toISOString()}`);
  console.log('');

  const beforeMetrics = await collect(before, orgSlug);
  const afterMetrics = await collect(after, orgSlug);

  const beforeProcess = beforeMetrics['process'] ?? null;
  const afterDocker = afterMetrics['docker'] ?? null;
  const afterProcess = afterMetrics['process'] ?? null;

  console.log('## Comparison');
  console.log('');
  console.log('| Metric                       | Before (process) | After (docker)   |');
  console.log('| ---------------------------- | ---------------- | ---------------- |');
  console.log(
    `| Step pass rate               | ${fmtPct(beforeProcess?.stepsPassed ?? 0, beforeProcess?.stepsRun ?? 0).padEnd(16)} | ${fmtPct(afterDocker?.stepsPassed ?? 0, afterDocker?.stepsRun ?? 0).padEnd(16)} |`,
  );
  console.log(
    `| p50 step latency             | ${fmtMs(beforeProcess?.p50StepMs ?? null).padEnd(16)} | ${fmtMs(afterDocker?.p50StepMs ?? null).padEnd(16)} |`,
  );
  console.log(
    `| p95 step latency             | ${fmtMs(beforeProcess?.p95StepMs ?? null).padEnd(16)} | ${fmtMs(afterDocker?.p95StepMs ?? null).padEnd(16)} |`,
  );
  console.log(
    `| p50 cold-start (sandbox)     | ${fmtMs(beforeProcess?.p50ColdStartMs ?? null).padEnd(16)} | ${fmtMs(afterDocker?.p50ColdStartMs ?? null).padEnd(16)} |`,
  );
  console.log(
    `| p95 cold-start (sandbox)     | ${fmtMs(beforeProcess?.p95ColdStartMs ?? null).padEnd(16)} | ${fmtMs(afterDocker?.p95ColdStartMs ?? null).padEnd(16)} |`,
  );
  console.log(`| OOM kills / day              | (see pino logs)  | (see pino logs)  |`);
  console.log(`| Egress blocks / day          | n/a              | (see proxy logs) |`);
  console.log('');
  console.log('Notes:');
  console.log(' - OOM kills are emitted as pino events (`sandbox.oom_suspected`) by the docker driver — count them from your log shipper.');
  console.log(' - Egress blocks are emitted by `runner-egress-proxy` as `egress.blocked` — count them from the proxy logs.');
  console.log(' - p50 cold-start `n/a` in the before window means SANDBOX_STARTED didn\'t exist yet (pre-#565). That\'s expected.');
  if (afterProcess && afterProcess.stepsRun > 0) {
    console.log(` - WARNING: the AFTER window still contains ${afterProcess.stepsRun} process-driver steps — verify the flip actually took effect.`);
  }
}

main()
  .then(() => process.exit(0))
  .catch((err) => {
    console.error('dogfood:bake-report: fatal', err);
    process.exit(1);
  });
